# Generated by Django 2.1.5 on 2019-02-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_program', models.CharField(max_length=255)),
                ('images', models.CharField(max_length=255)),
                ('deskripsi', models.CharField(max_length=1000)),
            ],
        ),
    ]
